-- https://github.com/julianazanelatto/devweek

CREATE DATABASE CANCER_MAMA
GO

USE CANCER_MAMA
GO

CREATE TABLE REGIAO(
    ID INT NOT NULL IDENTITY(1,1),
    NOME VARCHAR(20) NOT NULL,

    CONSTRAINT PK_REGIAO_ID PRIMARY KEY(ID)
)

CREATE TABLE FAIXA_ETARIA(
    ID INT NOT NULL IDENTITY(1,1),
    FAIXA_INICIAL INT NOT NULL,
    FAIXA_FINAL INT NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,

    CONSTRAINT PK_FAIXA_ETARIA_ID PRIMARY KEY(ID)

)

CREATE TABLE INCIDENCIA_EXAME(
    ID INT NOT NULL IDENTITY(1,1),
    REGIAO_ID INT NOT NULL,
    FAIXA_ETARIA_ID INT NOT NULL,
    MES INT NOT NULL,
    Ano INT NOT NULL,
    QUANT_EXAMES INT NOT NULL,

    CONSTRAINT PK_INCIDENCIA_EXAME_ID PRIMARY KEY(ID),
    CONSTRAINT FK_INCIDENCIA_REGIAO_ID FOREIGN KEY(REGIAO_ID) REFERENCES REGIAO (ID),
    CONSTRAINT FK_INCIDENCIA_FAIXA_ID FOREIGN KEY(FAIXA_ETARIA_ID) REFERENCES FAIXA_ETARIA (ID)
)