INSERT INTO REGIAO (NOME) VALUES ('Norte');
INSERT INTO REGIAO (NOME) VALUES ('Nordeste');
INSERT INTO REGIAO (NOME) VALUES ('Sudeste');
INSERT INTO REGIAO (NOME) VALUES ('Sul');
INSERT INTO REGIAO (NOME) VALUES ('Centro-Oeste');


INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('0','10','Até 10 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('11','14','Entre 11 e 14 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('15','19','Entre 15 e 19 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('20','24','Entre 20 e 24 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('25','29','Entre 25 e 29 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('30','34','Entre 30 e 34 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('35','39','Entre 35 e 39 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('40','44','Entre 40 e 44 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('45','49','Entre 45 e 49 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('50','54','Entre 50 e 54 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('55','59','Entre 55 e 59 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('60','64','Entre 60 e 64 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('65','69','Entre 65 e 69 anos');
INSERT INTO FAIXA_ETARIA (FAIXA_INICIAL,FAIXA_FINAL,DESCRICAO) VALUES ('70','150','Acima de 70');


INSERT INTO INCIDENCIA_EXAME (REGIAO_ID, Mes, ANO, FAIXA_ETARIA_ID, QUANT_EXAMES) VALUES (1,5,2020,2,1);
INSERT INTO INCIDENCIA_EXAME (REGIAO_ID, Mes, ANO, FAIXA_ETARIA_ID, QUANT_EXAMES) VALUES (1,5,2020,4,2);